 "",
  " Restaurant Name ",
  "  Second TEST Rafael Llera at Inktel ",
  " Restaurant\nNumber ",
  "  99998 ",
  " Restaurant Address ",
  "  2nd Test on Inktel Drive\nHialeah, Florida 33016\nMap It\n[http://maps.google.com/maps?q=2nd+Test+on+Inktel+Drive+Hialeah%2C+Florida+33016]\n",
  " Restaurant's Primary Phone Number ",
  "  (777) 777-7777 ",
  " Operator Name ",
  "\n Rafael Llera ",
  " Operator Phone Number ",
  "  (305) 302-0183 ",
  " Operator Email\nAddress ",
  "  rafael.llera@Inktel.com ",
  " Would you like to receive emails from\nthe VCA here: about Catering-related inquiries? ",
  "  Yes ",
  " Would you like to\nreceive text messages from the VCA here about Catering-related inquiries? ",
  "\n Yes ",
  " Catering Leader's Name ",
  "  Patrick Edwards ",
  " Catering Leader's Phone\nNumber ",
  "  (555) 555-5555 ",
  " Catering Leader's Email Address ",
  "\n ralphllera24@gmail.com ",
  " Would you like to receive emails from the VCA here\nabout Catering-related inquiries? ",
  "  Yes ",
  " Would you like to receive text\nmessages from the VCA here about Catering-related inquiries? ",
  "  Yes ",
  "\nEmail(s) where you'd like to receive your monthly invoice from Inktel ",
  "\n rafael.llera@inktel.com ",
  " Currently have a phone menu that’s capable of\nrouting Catering calls to a VCA phone number? ",
  "  No ",
  " Accept\nPay-Later/Pay-Upon-Arrival? ",
  "  Yes ",
  " Serve Chicken-Mini’s All Day? ",
  "  No\n",
  " Maximum $$ amount for pay-upon-pickup orders we can place without contacting\nyour restaurant? ",
  "  $257 ",
  " Do we need to confirm with your restaurant before\nplacing pickup order >1 hour? ",
  "  No ",
  " Do we need to confirm with your\nrestaurant before placing pickup order 30 min-1 hour? ",
  "  Yes ",
  " Do we need to\nconfirm with your restaurant before placing pickup order <30 min? ",
  "  No ",
  "\nAny other unique notes or Catering rules specific for your restaurant? ",
  "  This\nthe SECOND TEST. ",
  " Please Review the VCA Operator Agreement ",
  "\n [https://www.inktel.com/wp-content/plugins/gravityforms/images/tick.png] I have\nread and fully understand the VCA Operator Agreement Form\n\nPlease carefully read and review your contract before signing by clicking here\n[https://www.inktel.com/vca-contract-agreement/].\nVCA Operator Agreement Form Electoric Signature Consent\n [https://www.inktel.com/wp-content/plugins/gravityforms/images/tick.png] I\nagree to electronically sign the VCA Operator Agreement Form Document Signature\n [https://www.inktel.com/index.php?gf-signature=62f17c5b123298.20579716&amp;form-id=21&amp;field-id=49&amp;hash=688c2668196c77eec08e0066da5cad79956a49187f0564a2827595b9bbaedb79]\n[https://www.inktel.com/index.php?gf-signature=62f17c5b123298.20579716&form-id=21&field-id=49&hash=688c2668196c77eec08e0066da5cad79956a49187f0564a2827595b9bbaedb79]"
]